import { createClient } from '@/lib/supabase/server';

// ── Card type used throughout the player ─────────────────────────────────────

export interface FlashCard {
  id: string;
  source: 'official' | 'personal';
  /** HTML string generated by TipTap */
  front: string;
  /** HTML string generated by TipTap */
  back: string;
  hint: string | null;
  subjectName: string | null;
}

// ── Params ────────────────────────────────────────────────────────────────────

interface GetCardsParams {
  tenant: string;
  userId: string;
  subjectId: string | null;
  limit: number;
  mode: 'pending' | 'all';
  type: 'official' | 'personal';
}

// ── Main fetcher ──────────────────────────────────────────────────────────────

export async function getSessionCards({
  tenant,
  userId,
  subjectId,
  limit,
  mode,
  type,
}: GetCardsParams): Promise<FlashCard[]> {
  const supabase = await createClient();

  if (type === 'official') {
    return getOfficialCards({ supabase, tenant, userId, subjectId, limit, mode });
  }
  return getPersonalCards({ supabase, tenant, userId, subjectId, limit });
}

// ── Official cards (from questions table) ─────────────────────────────────────

async function getOfficialCards({
  supabase,
  tenant,
  userId,
  subjectId,
  limit,
  mode,
}: {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: any;
  tenant: string;
  userId: string;
  subjectId: string | null;
  limit: number;
  mode: 'pending' | 'all';
}): Promise<FlashCard[]> {
  const today = new Date().toISOString().split('T')[0];

  // Collect IDs to exclude (cards not due yet)
  let excludedIds: string[] = [];
  if (mode === 'pending') {
    try {
      const { data: notDue } = await supabase
        .from('user_flashcard_reviews')
        .select('question_id')
        .eq('user_id', userId)
        .eq('tenant_id', tenant)
        .not('question_id', 'is', null)
        .gt('next_review', today);

      excludedIds = (notDue ?? [])
        .map((r: { question_id: string | null }) => r.question_id)
        .filter(Boolean) as string[];
    } catch {
      // Table might not exist — ignore
    }
  }

  // Over-fetch to have enough after exclusion + shuffle
  const fetchLimit = Math.min(limit * 4, 400);

  let query = supabase
    .from('questions')
    .select('id, flashcard_front, flashcard_back, flashcard_hint, subjects(name)')
    .eq('tenant_id', tenant)
    .not('flashcard_front', 'is', null)
    .not('flashcard_back', 'is', null)
    .limit(fetchLimit);

  if (subjectId) {
    query = query.eq('subject_id', subjectId);
  }

  const { data: raw } = await query;
  if (!raw || raw.length === 0) return [];

  // Apply exclusion in JS (avoids complex NOT IN filter on untyped client)
  const pool =
    excludedIds.length > 0
      ? raw.filter((c: { id: string }) => !excludedIds.includes(c.id))
      : raw;

  // Fisher-Yates shuffle, then take limit
  type OfficialRaw = {
    id: string;
    flashcard_front: string;
    flashcard_back: string;
    flashcard_hint: string | null;
    subjects: unknown;
  };
  const shuffled = fisherYates(pool as OfficialRaw[]).slice(0, limit);

  return shuffled.map((c) => ({
      id: c.id,
      source: 'official' as const,
      front: c.flashcard_front,
      back: c.flashcard_back,
      hint: c.flashcard_hint ?? null,
      subjectName:
        (c.subjects as { name: string } | null)?.name ?? null,
    })
  );
}

// ── Personal cards (from user_flashcards table) ───────────────────────────────

async function getPersonalCards({
  supabase,
  tenant,
  userId,
  subjectId,
  limit,
}: {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: any;
  tenant: string;
  userId: string;
  subjectId: string | null;
  limit: number;
}): Promise<FlashCard[]> {
  try {
    let query = supabase
      .from('user_flashcards')
      .select('id, front, back, subjects(name)')
      .eq('user_id', userId)
      .eq('tenant_id', tenant)
      .limit(limit * 4);

    if (subjectId) {
      query = query.eq('subject_id', subjectId);
    }

    const { data: raw } = await query;
    if (!raw || raw.length === 0) return [];

    type PersonalRaw = { id: string; front: string; back: string; subjects: unknown };
    return fisherYates(raw as PersonalRaw[])
      .slice(0, limit)
      .map((c) => ({
        id: c.id,
        source: 'personal' as const,
        front: c.front,
        back: c.back,
        hint: null,
        subjectName:
          (c.subjects as { name: string } | null)?.name ?? null,
      }));
  } catch {
    return [];
  }
}

// ── Utils ─────────────────────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function fisherYates<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
